#include <asio/impl/src.hpp>
#include <asio/ssl/impl/src.hpp>
#include <SimpleWeb/crypto.hpp>
#include <SimpleWeb/client_http.hpp>
#include <SimpleWeb/server_http.hpp>
#include <SimpleWeb/client_https.hpp>
#include <SimpleWeb/server_https.hpp>
#include <SimpleWeb/client_ws.hpp>
#include <SimpleWeb/server_ws.hpp>
#include <SimpleWeb/client_wss.hpp>
#include <SimpleWeb/server_wss.hpp>
#include <leagueapi.hpp>