#ifndef MK1MF_BUILD
  /* auto-generated by crypto/Makefile for crypto/cversion.c */
  #define CFLAGS "X:/msys64/mingw64/bin/gcc.exe "
  #define PLATFORM "Windows"
  #define DATE ""
#endif
/* ~2DO: is the above ok? */



