#ifndef MK1MF_BUILD
  /* auto-generated by crypto/Makefile for crypto/cversion.c */
  #define CFLAGS "C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.11.25503/bin/HostX86/x86/cl.exe /DWIN32 /D_WINDOWS /W3"
  #define PLATFORM "Windows"
  #define DATE ""
#endif
/* ~2DO: is the above ok? */



