#pragma once
#include "../base_def.hpp" 
#include "EndOfGameLcdsPlayerParticipantStatsSummary.hpp"
#include "EndOfGameLcdsSpell.hpp"
#include "EndOfGameLcdsPointsPenalty.hpp"
#include "EndOfGameLcdsTeamInfo.hpp"
namespace lol {
  struct EndOfGameLcdsEndOfGameStats { 
    int32_t talentPointsGained;
    int32_t timeUntilNextFirstWinBonus;
    EndOfGameLcdsTeamInfo otherTeamInfo;
    int32_t eloChange;
    EndOfGameLcdsTeamInfo myTeamInfo;
    bool invalid;
    int32_t partyRewardsBonusIpEarned;
    uint64_t reportGameId;
    bool gameEndedInEarlySurrender;
    std::string queueType;
    int32_t firstWinBonus;
    uint64_t userId;
    bool teamEarlySurrendered;
    bool leveledUp;
    std::string difficulty;
    int32_t coOpVsAiMinutesLeftToday;
    std::string myTeamStatus;
    int32_t experienceTotal;
    int32_t experienceEarned;
    uint32_t gameLength;
    int32_t battleBoostIpEarned;
    uint64_t gameId;
    bool sendStatsToTournamentProvider;
    bool earlySurrenderAccomplice;
    bool imbalancedTeamsNoPoints;
    int32_t loyaltyBoostXpEarned;
    int32_t ipEarned;
    std::string summonerName;
    bool causedEarlySurrender;
    std::vector<EndOfGameLcdsPlayerParticipantStatsSummary> otherTeamPlayerParticipantStats;
    bool ranked;
    std::vector<std::string> gameMutators;
    uint64_t previousXpTotal;
    std::string roomName;
    int32_t queueBonusEarned;
    int32_t elo;
    uint64_t previousLevel;
    std::vector<EndOfGameLcdsPointsPenalty> pointsPenalties;
    int32_t basePoints;
    std::string gameType;
    std::string gameMode;
    std::string roomPassword;
    int32_t boostIpEarned;
    int32_t rpEarned;
    int32_t ipTotal;
    std::vector<EndOfGameLcdsSpell> newSpells;
    int32_t skinIndex;
    int32_t customMsecsUntilReset;
    int32_t completionBonusPoints;
    int32_t customMinutesLeftToday;
    std::vector<EndOfGameLcdsPlayerParticipantStatsSummary> teamPlayerParticipantStats;
    int32_t skinId;
    int32_t boostXpEarned;
    int32_t loyaltyBoostIpEarned;
    int32_t coOpVsAiMsecsUntilReset;
    int32_t odinBonusIp; 
  };
  inline void to_json(json& j, const EndOfGameLcdsEndOfGameStats& v) {
    j["talentPointsGained"] = v.talentPointsGained; 
    j["timeUntilNextFirstWinBonus"] = v.timeUntilNextFirstWinBonus; 
    j["otherTeamInfo"] = v.otherTeamInfo; 
    j["eloChange"] = v.eloChange; 
    j["myTeamInfo"] = v.myTeamInfo; 
    j["invalid"] = v.invalid; 
    j["partyRewardsBonusIpEarned"] = v.partyRewardsBonusIpEarned; 
    j["reportGameId"] = v.reportGameId; 
    j["gameEndedInEarlySurrender"] = v.gameEndedInEarlySurrender; 
    j["queueType"] = v.queueType; 
    j["firstWinBonus"] = v.firstWinBonus; 
    j["userId"] = v.userId; 
    j["teamEarlySurrendered"] = v.teamEarlySurrendered; 
    j["leveledUp"] = v.leveledUp; 
    j["difficulty"] = v.difficulty; 
    j["coOpVsAiMinutesLeftToday"] = v.coOpVsAiMinutesLeftToday; 
    j["myTeamStatus"] = v.myTeamStatus; 
    j["experienceTotal"] = v.experienceTotal; 
    j["experienceEarned"] = v.experienceEarned; 
    j["gameLength"] = v.gameLength; 
    j["battleBoostIpEarned"] = v.battleBoostIpEarned; 
    j["gameId"] = v.gameId; 
    j["sendStatsToTournamentProvider"] = v.sendStatsToTournamentProvider; 
    j["earlySurrenderAccomplice"] = v.earlySurrenderAccomplice; 
    j["imbalancedTeamsNoPoints"] = v.imbalancedTeamsNoPoints; 
    j["loyaltyBoostXpEarned"] = v.loyaltyBoostXpEarned; 
    j["ipEarned"] = v.ipEarned; 
    j["summonerName"] = v.summonerName; 
    j["causedEarlySurrender"] = v.causedEarlySurrender; 
    j["otherTeamPlayerParticipantStats"] = v.otherTeamPlayerParticipantStats; 
    j["ranked"] = v.ranked; 
    j["gameMutators"] = v.gameMutators; 
    j["previousXpTotal"] = v.previousXpTotal; 
    j["roomName"] = v.roomName; 
    j["queueBonusEarned"] = v.queueBonusEarned; 
    j["elo"] = v.elo; 
    j["previousLevel"] = v.previousLevel; 
    j["pointsPenalties"] = v.pointsPenalties; 
    j["basePoints"] = v.basePoints; 
    j["gameType"] = v.gameType; 
    j["gameMode"] = v.gameMode; 
    j["roomPassword"] = v.roomPassword; 
    j["boostIpEarned"] = v.boostIpEarned; 
    j["rpEarned"] = v.rpEarned; 
    j["ipTotal"] = v.ipTotal; 
    j["newSpells"] = v.newSpells; 
    j["skinIndex"] = v.skinIndex; 
    j["customMsecsUntilReset"] = v.customMsecsUntilReset; 
    j["completionBonusPoints"] = v.completionBonusPoints; 
    j["customMinutesLeftToday"] = v.customMinutesLeftToday; 
    j["teamPlayerParticipantStats"] = v.teamPlayerParticipantStats; 
    j["skinId"] = v.skinId; 
    j["boostXpEarned"] = v.boostXpEarned; 
    j["loyaltyBoostIpEarned"] = v.loyaltyBoostIpEarned; 
    j["coOpVsAiMsecsUntilReset"] = v.coOpVsAiMsecsUntilReset; 
    j["odinBonusIp"] = v.odinBonusIp; 
  }
  inline void from_json(const json& j, EndOfGameLcdsEndOfGameStats& v) {
    v.talentPointsGained = j.at("talentPointsGained").get<int32_t>(); 
    v.timeUntilNextFirstWinBonus = j.at("timeUntilNextFirstWinBonus").get<int32_t>(); 
    v.otherTeamInfo = j.at("otherTeamInfo").get<EndOfGameLcdsTeamInfo>(); 
    v.eloChange = j.at("eloChange").get<int32_t>(); 
    v.myTeamInfo = j.at("myTeamInfo").get<EndOfGameLcdsTeamInfo>(); 
    v.invalid = j.at("invalid").get<bool>(); 
    v.partyRewardsBonusIpEarned = j.at("partyRewardsBonusIpEarned").get<int32_t>(); 
    v.reportGameId = j.at("reportGameId").get<uint64_t>(); 
    v.gameEndedInEarlySurrender = j.at("gameEndedInEarlySurrender").get<bool>(); 
    v.queueType = j.at("queueType").get<std::string>(); 
    v.firstWinBonus = j.at("firstWinBonus").get<int32_t>(); 
    v.userId = j.at("userId").get<uint64_t>(); 
    v.teamEarlySurrendered = j.at("teamEarlySurrendered").get<bool>(); 
    v.leveledUp = j.at("leveledUp").get<bool>(); 
    v.difficulty = j.at("difficulty").get<std::string>(); 
    v.coOpVsAiMinutesLeftToday = j.at("coOpVsAiMinutesLeftToday").get<int32_t>(); 
    v.myTeamStatus = j.at("myTeamStatus").get<std::string>(); 
    v.experienceTotal = j.at("experienceTotal").get<int32_t>(); 
    v.experienceEarned = j.at("experienceEarned").get<int32_t>(); 
    v.gameLength = j.at("gameLength").get<uint32_t>(); 
    v.battleBoostIpEarned = j.at("battleBoostIpEarned").get<int32_t>(); 
    v.gameId = j.at("gameId").get<uint64_t>(); 
    v.sendStatsToTournamentProvider = j.at("sendStatsToTournamentProvider").get<bool>(); 
    v.earlySurrenderAccomplice = j.at("earlySurrenderAccomplice").get<bool>(); 
    v.imbalancedTeamsNoPoints = j.at("imbalancedTeamsNoPoints").get<bool>(); 
    v.loyaltyBoostXpEarned = j.at("loyaltyBoostXpEarned").get<int32_t>(); 
    v.ipEarned = j.at("ipEarned").get<int32_t>(); 
    v.summonerName = j.at("summonerName").get<std::string>(); 
    v.causedEarlySurrender = j.at("causedEarlySurrender").get<bool>(); 
    v.otherTeamPlayerParticipantStats = j.at("otherTeamPlayerParticipantStats").get<std::vector<EndOfGameLcdsPlayerParticipantStatsSummary>>(); 
    v.ranked = j.at("ranked").get<bool>(); 
    v.gameMutators = j.at("gameMutators").get<std::vector<std::string>>(); 
    v.previousXpTotal = j.at("previousXpTotal").get<uint64_t>(); 
    v.roomName = j.at("roomName").get<std::string>(); 
    v.queueBonusEarned = j.at("queueBonusEarned").get<int32_t>(); 
    v.elo = j.at("elo").get<int32_t>(); 
    v.previousLevel = j.at("previousLevel").get<uint64_t>(); 
    v.pointsPenalties = j.at("pointsPenalties").get<std::vector<EndOfGameLcdsPointsPenalty>>(); 
    v.basePoints = j.at("basePoints").get<int32_t>(); 
    v.gameType = j.at("gameType").get<std::string>(); 
    v.gameMode = j.at("gameMode").get<std::string>(); 
    v.roomPassword = j.at("roomPassword").get<std::string>(); 
    v.boostIpEarned = j.at("boostIpEarned").get<int32_t>(); 
    v.rpEarned = j.at("rpEarned").get<int32_t>(); 
    v.ipTotal = j.at("ipTotal").get<int32_t>(); 
    v.newSpells = j.at("newSpells").get<std::vector<EndOfGameLcdsSpell>>(); 
    v.skinIndex = j.at("skinIndex").get<int32_t>(); 
    v.customMsecsUntilReset = j.at("customMsecsUntilReset").get<int32_t>(); 
    v.completionBonusPoints = j.at("completionBonusPoints").get<int32_t>(); 
    v.customMinutesLeftToday = j.at("customMinutesLeftToday").get<int32_t>(); 
    v.teamPlayerParticipantStats = j.at("teamPlayerParticipantStats").get<std::vector<EndOfGameLcdsPlayerParticipantStatsSummary>>(); 
    v.skinId = j.at("skinId").get<int32_t>(); 
    v.boostXpEarned = j.at("boostXpEarned").get<int32_t>(); 
    v.loyaltyBoostIpEarned = j.at("loyaltyBoostIpEarned").get<int32_t>(); 
    v.coOpVsAiMsecsUntilReset = j.at("coOpVsAiMsecsUntilReset").get<int32_t>(); 
    v.odinBonusIp = j.at("odinBonusIp").get<int32_t>(); 
  }
}